// GENERATED by scripts/build-garment-photos.mjs — do not edit by hand.
//
// Openly-licensed photographs of real garments, used as the closet's imagery.
// Every entry carries the licence it ships under and its attribution; anything
// that arrived without one was dropped rather than published.
//
// 40 photographs.

export interface GarmentPhoto {
  slug: string;
  path: string;
  license: string;
  attribution: string | null;
  landing_url: string;
}

export const GARMENT_PHOTOS: GarmentPhoto[] = [
 {
  "slug": "backpack-daypack",
  "path": "wardrobe/garment/backpack-daypack.webp",
  "license": "CC BY-SA 3.0",
  "attribution": "Ironmonger",
  "landing_url": "https://commons.wikimedia.org/wiki/File:Tropical_Rucksack_1.JPG"
 },
 {
  "slug": "beanie-rib",
  "path": "wardrobe/garment/beanie-rib.webp",
  "license": "Public domain",
  "attribution": "No machine-readable author provided. CommonsHelper2 Bot assumed (based on copyright claims).",
  "landing_url": "https://commons.wikimedia.org/wiki/File:Entrelac-hat.jpg"
 },
 {
  "slug": "belt-leather",
  "path": "wardrobe/garment/belt-leather.webp",
  "license": "Public domain",
  "attribution": "No machine-readable author provided. Joeyramoney~commonswiki assumed (based on copyright claims).",
  "landing_url": "https://commons.wikimedia.org/wiki/File:Leather_belt_%26_buckle.jpg"
 },
 {
  "slug": "boot-chelsea",
  "path": "wardrobe/garment/boot-chelsea.webp",
  "license": "Public domain",
  "attribution": "No machine-readable author provided. Back ache assumed (based on copyright claims).",
  "landing_url": "https://commons.wikimedia.org/wiki/File:VeggieChelseaBoots.jpg"
 },
 {
  "slug": "camisole-silk",
  "path": "wardrobe/garment/camisole-silk.webp",
  "license": "CC BY 4.0",
  "attribution": "Bendon",
  "landing_url": "https://commons.wikimedia.org/wiki/File:Camisole_(AM_2000.93.96-1).jpg"
 },
 {
  "slug": "derby-plain",
  "path": "wardrobe/garment/derby-plain.webp",
  "license": "CC BY-SA 3.0",
  "attribution": "Kan8eDie",
  "landing_url": "https://commons.wikimedia.org/wiki/File:Derby_shoe1.jpg"
 },
 {
  "slug": "duffle-weekender",
  "path": "wardrobe/garment/duffle-weekender.webp",
  "license": "CC BY-SA 3.0",
  "attribution": "Bahamut0013",
  "landing_url": "https://commons.wikimedia.org/wiki/File:Seabag.jpg"
 },
 {
  "slug": "gilet-quilted",
  "path": "wardrobe/garment/gilet-quilted.webp",
  "license": "CC BY-SA 4.0",
  "attribution": "Jjanhone",
  "landing_url": "https://commons.wikimedia.org/wiki/File:Wilson_body_warmer_navy_men.jpg"
 },
 {
  "slug": "hoodie-oversized",
  "path": "wardrobe/garment/hoodie-oversized.webp",
  "license": "CC BY-SA 3.0",
  "attribution": "Davidcanogomez",
  "landing_url": "https://commons.wikimedia.org/wiki/File:Sudadera_urban.jpg"
 },
 {
  "slug": "leggings-yoga",
  "path": "wardrobe/garment/leggings-yoga.webp",
  "license": "CC BY-SA 4.0",
  "attribution": "Msadp06",
  "landing_url": "https://commons.wikimedia.org/wiki/File:Legging.masculina_da_adidas.JPG"
 },
 {
  "slug": "loafer-penny",
  "path": "wardrobe/garment/loafer-penny.webp",
  "license": "CC BY 2.0",
  "attribution": "Robert  Sheie from Minneapolis, USA",
  "landing_url": "https://commons.wikimedia.org/wiki/File:Presidio_Loafer.jpg"
 },
 {
  "slug": "necklace-chain",
  "path": "wardrobe/garment/necklace-chain.webp",
  "license": "CC BY-SA 3.0",
  "attribution": "Durova",
  "landing_url": "https://commons.wikimedia.org/wiki/File:Chain_pearl_necklace.jpg"
 },
 {
  "slug": "oxford-captoe",
  "path": "wardrobe/garment/oxford-captoe.webp",
  "license": "CC BY-SA 3.0",
  "attribution": "Kan8eDie",
  "landing_url": "https://commons.wikimedia.org/wiki/File:Oxford_shoe1.jpg"
 },
 {
  "slug": "pashmina-shawl",
  "path": "wardrobe/garment/pashmina-shawl.webp",
  "license": "Public domain",
  "attribution": "Bettenburg at German Wikipedia",
  "landing_url": "https://commons.wikimedia.org/wiki/File:Pashmina-schals_orig.jpg"
 },
 {
  "slug": "slip-on-suede",
  "path": "wardrobe/garment/slip-on-suede.webp",
  "license": "CC BY-SA 3.0",
  "attribution": "Corbeau",
  "landing_url": "https://commons.wikimedia.org/wiki/File:Paar_herenschoenen,_bruine_su%C3%A8de_met_lak,_%E2%80%9CCorbeau%E2%80%9D,_objectnr_87299-1-2.JPG"
 },
 {
  "slug": "sneaker-white",
  "path": "wardrobe/garment/sneaker-white.webp",
  "license": "Public domain",
  "attribution": "Anonymous",
  "landing_url": "https://commons.wikimedia.org/wiki/File:Feiyue_White.jpg"
 },
 {
  "slug": "socks-crew",
  "path": "wardrobe/garment/socks-crew.webp",
  "license": "CC BY-SA 2.0 uk",
  "attribution": "David Jackson",
  "landing_url": "https://commons.wikimedia.org/wiki/File:BLW_Pair_of_socks.jpg"
 },
 {
  "slug": "suit-jacket",
  "path": "wardrobe/garment/suit-jacket.webp",
  "license": "CC BY-SA 2.0",
  "attribution": "Paul Goyette",
  "landing_url": "https://commons.wikimedia.org/wiki/File:Grey_and_navy_suit_on_mannequin.jpg"
 },
 {
  "slug": "sunglasses-wayfarer",
  "path": "wardrobe/garment/sunglasses-wayfarer.webp",
  "license": "CC BY 2.5",
  "attribution": "Rich Niewiroski Jr.",
  "landing_url": "https://commons.wikimedia.org/wiki/File:RayBanWayfarer.jpg"
 },
 {
  "slug": "trail-runner",
  "path": "wardrobe/garment/trail-runner.webp",
  "license": "CC BY-SA 3.0",
  "attribution": "Jean-Yves Couput",
  "landing_url": "https://commons.wikimedia.org/wiki/File:Trail_running_shoe.jpg"
 },
 {
  "slug": "waistcoat",
  "path": "wardrobe/garment/waistcoat.webp",
  "license": "CC BY-SA 3.0",
  "attribution": null,
  "landing_url": "https://commons.wikimedia.org/wiki/File:Waistcoat.jpg"
 },
 {
  "slug": "watch-dress-steel",
  "path": "wardrobe/garment/watch-dress-steel.webp",
  "license": "CC BY-SA 3.0",
  "attribution": "J. Lunau",
  "landing_url": "https://commons.wikimedia.org/wiki/File:Junghans_Mega.jpg"
 },
 {
  "slug": "in-banarasi-silk-saree",
  "path": "wardrobe/garment/in-banarasi-silk-saree.webp",
  "license": "AI-generated for this project",
  "attribution": null,
  "landing_url": ""
 },
 {
  "slug": "in-lehenga-choli",
  "path": "wardrobe/garment/in-lehenga-choli.webp",
  "license": "AI-generated for this project",
  "attribution": null,
  "landing_url": ""
 },
 {
  "slug": "in-kurti-palazzo-set",
  "path": "wardrobe/garment/in-kurti-palazzo-set.webp",
  "license": "AI-generated for this project",
  "attribution": null,
  "landing_url": ""
 },
 {
  "slug": "in-salwar-kameez",
  "path": "wardrobe/garment/in-salwar-kameez.webp",
  "license": "AI-generated for this project",
  "attribution": null,
  "landing_url": ""
 },
 {
  "slug": "in-anarkali-gown",
  "path": "wardrobe/garment/in-anarkali-gown.webp",
  "license": "AI-generated for this project",
  "attribution": null,
  "landing_url": ""
 },
 {
  "slug": "in-sharara-set",
  "path": "wardrobe/garment/in-sharara-set.webp",
  "license": "AI-generated for this project",
  "attribution": null,
  "landing_url": ""
 },
 {
  "slug": "in-mekhela-chador",
  "path": "wardrobe/garment/in-mekhela-chador.webp",
  "license": "AI-generated for this project",
  "attribution": null,
  "landing_url": ""
 },
 {
  "slug": "in-kurta-pajama",
  "path": "wardrobe/garment/in-kurta-pajama.webp",
  "license": "AI-generated for this project",
  "attribution": null,
  "landing_url": ""
 },
 {
  "slug": "in-sherwani",
  "path": "wardrobe/garment/in-sherwani.webp",
  "license": "AI-generated for this project",
  "attribution": null,
  "landing_url": ""
 },
 {
  "slug": "in-dhoti-kurta",
  "path": "wardrobe/garment/in-dhoti-kurta.webp",
  "license": "AI-generated for this project",
  "attribution": null,
  "landing_url": ""
 },
 {
  "slug": "in-churidar-kurta",
  "path": "wardrobe/garment/in-churidar-kurta.webp",
  "license": "AI-generated for this project",
  "attribution": null,
  "landing_url": ""
 },
 {
  "slug": "in-bandhgala-suit",
  "path": "wardrobe/garment/in-bandhgala-suit.webp",
  "license": "AI-generated for this project",
  "attribution": null,
  "landing_url": ""
 },
 {
  "slug": "in-pathani-suit",
  "path": "wardrobe/garment/in-pathani-suit.webp",
  "license": "AI-generated for this project",
  "attribution": null,
  "landing_url": ""
 },
 {
  "slug": "in-nehru-jacket-set",
  "path": "wardrobe/garment/in-nehru-jacket-set.webp",
  "license": "AI-generated for this project",
  "attribution": null,
  "landing_url": ""
 },
 {
  "slug": "in-indo-western-jacket-set",
  "path": "wardrobe/garment/in-indo-western-jacket-set.webp",
  "license": "AI-generated for this project",
  "attribution": null,
  "landing_url": ""
 },
 {
  "slug": "in-patiala-suit",
  "path": "wardrobe/garment/in-patiala-suit.webp",
  "license": "AI-generated for this project",
  "attribution": null,
  "landing_url": ""
 },
 {
  "slug": "in-mundu-lungi-outfit",
  "path": "wardrobe/garment/in-mundu-lungi-outfit.webp",
  "license": "AI-generated for this project",
  "attribution": null,
  "landing_url": ""
 },
 {
  "slug": "in-ghagra-choli",
  "path": "wardrobe/garment/in-ghagra-choli.webp",
  "license": "AI-generated for this project",
  "attribution": null,
  "landing_url": ""
 }
];
