/**
 * THE WISHLIST'S ADDRESSES, in one place.
 *
 *   /wishlist   the room
 *   /profile    the House — the door this room is reached through, and the
 *               way back it owes the reader (it has no slot on the house bar)
 *   /open       where a cold start with no wardrobe goes (lead ruling R7,
 *               matching the tabs and the two other rooms off the bar)
 *
 * THE ONE CAST IN THIS FEATURE, and why it is here rather than scattered.
 * expo-router's typed routes build their union in app/.expo/types/router.d.ts,
 * which is GENERATED by a running dev server — a route added while no server
 * is watching is not in the union yet, and `router.push('/wishlist')` is a
 * type error against a file the compiler is right about and the app is not.
 * The cast is confined to this module so that when the union regenerates,
 * deleting three `as` keywords is the whole clean-up. The dressing room's
 * precedent (components/furniture/addresses.ts), adopted rather than
 * reinvented.
 */
import type { Href } from 'expo-router';

const href = (path: string): Href => path as unknown as Href;

/** The room itself. */
export const WISHLIST: Href = href('/wishlist');

/** The House — where this room is reached from, and the way back. */
export const HOUSE: Href = href('/profile');

/** The door. A cold start with no wardrobe open goes here. */
export const DOOR: Href = href('/open');
