/**
 * THE CALENDAR'S ADDRESSES, in one place.
 *
 *   /calendar                    the month containing today
 *   /calendar?day=YYYY-MM-DD     that month, with that day's page open
 *
 * THE ONE CAST IN THIS FEATURE, and why it is confined here — the same reason
 * the dressing room and the Looks room state (their addresses.ts files).
 * expo-router's typed routes build their union in app/.expo/types/router.d.ts,
 * which is GENERATED by a running dev server; a route added while no server is
 * watching is not in that union yet, so `router.push('/calendar')` is a type
 * error about a file the compiler is right about and the app is not. Keeping
 * the cast in one module means that when the union regenerates, deleting two
 * `as` keywords is the whole clean-up and no screen moves.
 *
 * The day is percent-encoded on the way in even though a 'YYYY-MM-DD' holds
 * nothing a query string reads as punctuation: the encode costs nothing, and
 * the day this parameter starts carrying something else it is already safe.
 */
import type { Href } from 'expo-router';

const href = (path: string): Href => path as unknown as Href;

/** The month room. With a day, the month it is in, that day's page open. */
export function calendarHref(day?: string | null): Href {
  return href(day ? `/calendar?day=${encodeURIComponent(day)}` : '/calendar');
}

/** Home, for the way back when there is nothing to pop. Back means Today. */
export const TODAY: Href = href('/');
