/**
 * THE LOOKS ROOM'S ADDRESSES, in one place.
 *
 *   /outfits            the room
 *   /outfits/<lookId>   one look, open
 *
 * THE ONE CAST IN THIS FEATURE, and why it is confined here — the same reason
 * the dressing room states (app/src/components/furniture/addresses.ts).
 * expo-router's typed routes build their union in app/.expo/types/router.d.ts,
 * which is GENERATED by a running dev server; a route added while no server is
 * watching is not in that union yet, so `router.push('/outfits')` is a type
 * error about a file the compiler is right about and the app is not. Keeping
 * the cast in one module means that when the union regenerates, deleting three
 * `as` keywords is the whole clean-up and no screen moves.
 *
 * The id is percent-encoded. Ids are opaque strings minted by the provider
 * (lib/wardrobe.tsx newId), and an opaque string is exactly the kind that
 * eventually holds a character a path reads as punctuation.
 */
import type { Href } from 'expo-router';

const href = (path: string): Href => path as unknown as Href;

/** The room. */
export const LOOKS: Href = href('/outfits');

/** One look, open. */
export function lookHref(id: string): Href {
  return href(`/outfits/${encodeURIComponent(id)}`);
}

/**
 * Where the Closet is, for the way back when there is nothing to pop.
 *
 * The Closet is the room that sends people here (its Looks rail links by
 * address only), so it is where "back" means even on a cold deep link.
 */
export const CLOSET: Href = href('/closet');
