/**
 * THE DRESSING ROOM'S ADDRESSES, in one place.
 *
 *   /furniture                          the room
 *   /furniture/<placeId>                one place, open
 *   /furniture?file=<itemId>            the room, asking WHICH PLACE
 *   /furniture/<placeId>?file=<itemId>  the place, asking WHICH COMPARTMENT
 *
 * THE ONE CAST IN THIS FEATURE, and why it is here rather than scattered.
 * expo-router's typed routes build their union in app/.expo/types/router.d.ts,
 * which is GENERATED by a running dev server — a route added while no server is
 * watching is not in the union yet, and `router.push('/furniture')` is a type
 * error against a file the compiler is right about and the app is not. The cast
 * is confined to this module so that when the union regenerates, deleting four
 * `as` keywords is the whole clean-up and nothing else in the feature moves.
 *
 * The item id is percent-encoded: ids are opaque strings minted by the
 * provider, and an opaque string is exactly the kind that eventually contains
 * a character a query string reads as punctuation.
 */
import type { Href } from 'expo-router';

const href = (path: string): Href => path as unknown as Href;

/** The room. With an item, the room asking which place it lives in. */
export function roomHref(file?: string | null): Href {
  return href(file ? `/furniture?file=${encodeURIComponent(file)}` : '/furniture');
}

/** One place. With an item, the place asking which compartment. */
export function placeHref(id: string, file?: string | null): Href {
  return href(file ? `/furniture/${id}?file=${encodeURIComponent(file)}` : `/furniture/${id}`);
}

/** Where the closet is, for the way back when there is nothing to pop. */
export const CLOSET: Href = href('/closet');
